image: node

stages:
  - setup
  - lint

variables:
  CACHE_KEY: "node_modulges-$CI_COMMIT_REF_SLUG"

node-setup:
  stage: setup
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules

eslint:
  stage: lint
  script:
    - npm run lint
  dependencies:
    - node-setup

prettier:
  stage: lint
  script:
    - npx prettier --check "**/*.{js,jsx,ts,tsx,json,md}"
  dependencies:
    - node-setup
